[build]
  publish = "hugo-hero-theme/tree/master/exampleSite/public"
  command = "cd hugo-hero-theme/tree/master/exampleSite && hugo --themesDir ../"

[build.environment]
  HUGO_VERSION = "0.82.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"
