name = "Hero"
license = "MIT"
licenselink = "https://github.com/zerostaticthemes/hugo-hero-theme/blob/master/LICENSE"
description = "Hero is a multipurpose theme with fullscreen hero images and fullwidth sections. It contains content types for a business or portfolio site."

homepage = "https://github.com/severseven/hugo-hero-theme"
demosite = "https://dazzling-hawking-2420f0.netlify.app/"

tags = ["responsive","minimal","clean","company","portfolio","bootstrap","zerostatic"]
features = ["services","work","fullwidth","hero images"]

[author]
  name = "Sev"
  homepage = "https://www.coperarte.it"
