name = "CoperArte"
license = "MIT"
licenselink = "https://github.com/zerostaticthemes/hugo-hero-theme/blob/master/LICENSE"
description = "Coperarte è una azienda leader nel settore dei servizi ICT"

homepage = "https://github.com/severseven/hugo-hero-theme"
demosite = "https://dazzling-hawking-2420f0.netlify.app/"

tags = ["responsive","minimal","clean","company","portfolio","bootstrap","zerostatic"]
features = ["services","work","fullwidth","hero images"]

[author]
  name = "Sev"
  homepage = "https://www.coperarte.it"
